// version which we are using in our project

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: coffeeShop.proto

// we define a package namespace for our proto file to prevent naming conflicts

package coffeeshop_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeShop_GetMenu_FullMethodName        = "/coffeeShop.CoffeeShop/GetMenu"
	CoffeeShop_PlaceOrder_FullMethodName     = "/coffeeShop.CoffeeShop/PlaceOrder"
	CoffeeShop_GetOrderStatus_FullMethodName = "/coffeeShop.CoffeeShop/GetOrderStatus"
)

// CoffeeShopClient is the client API for CoffeeShop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// we define the CoffeeShop service with its RPC methods
type CoffeeShopClient interface {
	// RPC method to get menu
	GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Menu], error)
	// RPC method to place an order
	PlaceOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderConfirmation, error)
	// RPC method to get order status
	GetOrderStatus(ctx context.Context, in *OrderStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderStatus], error)
}

type coffeeShopClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeShopClient(cc grpc.ClientConnInterface) CoffeeShopClient {
	return &coffeeShopClient{cc}
}

func (c *coffeeShopClient) GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Menu], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoffeeShop_ServiceDesc.Streams[0], CoffeeShop_GetMenu_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MenuRequest, Menu]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShop_GetMenuClient = grpc.ServerStreamingClient[Menu]

func (c *coffeeShopClient) PlaceOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderConfirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderConfirmation)
	err := c.cc.Invoke(ctx, CoffeeShop_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeShopClient) GetOrderStatus(ctx context.Context, in *OrderStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoffeeShop_ServiceDesc.Streams[1], CoffeeShop_GetOrderStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderStatusRequest, OrderStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShop_GetOrderStatusClient = grpc.ServerStreamingClient[OrderStatus]

// CoffeeShopServer is the server API for CoffeeShop service.
// All implementations must embed UnimplementedCoffeeShopServer
// for forward compatibility.
//
// we define the CoffeeShop service with its RPC methods
type CoffeeShopServer interface {
	// RPC method to get menu
	GetMenu(*MenuRequest, grpc.ServerStreamingServer[Menu]) error
	// RPC method to place an order
	PlaceOrder(context.Context, *Order) (*OrderConfirmation, error)
	// RPC method to get order status
	GetOrderStatus(*OrderStatusRequest, grpc.ServerStreamingServer[OrderStatus]) error
	mustEmbedUnimplementedCoffeeShopServer()
}

// UnimplementedCoffeeShopServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeShopServer struct{}

func (UnimplementedCoffeeShopServer) GetMenu(*MenuRequest, grpc.ServerStreamingServer[Menu]) error {
	return status.Errorf(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedCoffeeShopServer) PlaceOrder(context.Context, *Order) (*OrderConfirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedCoffeeShopServer) GetOrderStatus(*OrderStatusRequest, grpc.ServerStreamingServer[OrderStatus]) error {
	return status.Errorf(codes.Unimplemented, "method GetOrderStatus not implemented")
}
func (UnimplementedCoffeeShopServer) mustEmbedUnimplementedCoffeeShopServer() {}
func (UnimplementedCoffeeShopServer) testEmbeddedByValue()                    {}

// UnsafeCoffeeShopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeShopServer will
// result in compilation errors.
type UnsafeCoffeeShopServer interface {
	mustEmbedUnimplementedCoffeeShopServer()
}

func RegisterCoffeeShopServer(s grpc.ServiceRegistrar, srv CoffeeShopServer) {
	// If the following call pancis, it indicates UnimplementedCoffeeShopServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeShop_ServiceDesc, srv)
}

func _CoffeeShop_GetMenu_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MenuRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoffeeShopServer).GetMenu(m, &grpc.GenericServerStream[MenuRequest, Menu]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShop_GetMenuServer = grpc.ServerStreamingServer[Menu]

func _CoffeeShop_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShop_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServer).PlaceOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeShop_GetOrderStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoffeeShopServer).GetOrderStatus(m, &grpc.GenericServerStream[OrderStatusRequest, OrderStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShop_GetOrderStatusServer = grpc.ServerStreamingServer[OrderStatus]

// CoffeeShop_ServiceDesc is the grpc.ServiceDesc for CoffeeShop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeShop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coffeeShop.CoffeeShop",
	HandlerType: (*CoffeeShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _CoffeeShop_PlaceOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMenu",
			Handler:       _CoffeeShop_GetMenu_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOrderStatus",
			Handler:       _CoffeeShop_GetOrderStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coffeeShop.proto",
}
